kind: pipeline
name: default

steps:
  - name: app-test
    image: bluerain/veemoe-cloud:build
    pull: true
    commands:
      - shards --production
      - VEEMOE_CLOUD_ENV=test crystal spec

  - name: assets-build
    image: node:stretch
    commands:
      - npm install --prefix ./assets
      - npm run deploy --prefix ./assets

  - name: app-build
    image: bluerain/veemoe-cloud:build
    pull: true
    commands:
      - shards build -Dpreview_mt --release --progress --production
      - crystal sam.cr -- digests:make
      - crystal sam.cr -- digests:clean_undigested

  - name: app-image-push
    image: plugins/docker
    settings:
      repo: bluerain/veemoe-cloud
      username: bluerain
      password:
        from_secret: docker_password
      dockerfile: Dockerfile
      tags: latest
    when:
      branch:
        - master
      event:
        - push
