CREATE TABLE migration_versions (id integer PRIMARY KEY AUTOINCREMENT, version text NOT NULL);
CREATE TABLE workspaces (id integer PRIMARY KEY AUTOINCREMENT, name text NOT NULL, description text NOT NULL, is_protected integer NOT NULL DEFAULT true, created_at text NOT NULL, updated_at text NOT NULL);
CREATE UNIQUE INDEX workspaces_name_idx ON workspaces (name);
CREATE TABLE IF NOT EXISTS "matches"(id integer PRIMARY KEY, expression text NOT NULL, workspace_id integer NOT NULL, created_at text NOT NULL, updated_at text NOT NULL,FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE UNIQUE INDEX matches_workspace_id_expression_idx ON matches (workspace_id,expression);
CREATE TABLE IF NOT EXISTS "pipes"(id integer PRIMARY KEY, name text NOT NULL, query_params text NOT NULL, workspace_id integer NOT NULL, created_at text NOT NULL, updated_at text NOT NULL,FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE UNIQUE INDEX pipes_workspace_id_name_idx ON pipes (workspace_id,name);
CREATE TABLE IF NOT EXISTS "styles"(id integer PRIMARY KEY, name text NOT NULL, description text NOT NULL, workspace_id integer NOT NULL, created_at text NOT NULL, updated_at text NOT NULL,FOREIGN KEY (workspace_id) REFERENCES workspaces(id) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE UNIQUE INDEX styles_workspace_id_name_idx ON styles (workspace_id,name);
CREATE TABLE IF NOT EXISTS "pipes_styles"(pipe_id integer NOT NULL, style_id integer NOT NULL,FOREIGN KEY (pipe_id) REFERENCES pipes(id) ON UPDATE RESTRICT ON DELETE CASCADE,FOREIGN KEY (style_id) REFERENCES styles(id) ON UPDATE RESTRICT ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS "matches_styles"(match_id integer NOT NULL, style_id integer NOT NULL,FOREIGN KEY (match_id) REFERENCES matches(id) ON UPDATE RESTRICT ON DELETE CASCADE,FOREIGN KEY (style_id) REFERENCES styles(id) ON UPDATE RESTRICT ON DELETE CASCADE);
